const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
(async () => {
  const root = path.resolve(__dirname, '..');
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'moye-ui-'));
  const fixture = path.join(temp, '测试文档.md');
  const image = path.join(root, 'assets', 'mountains.svg');
  await fs.copyFile(image, path.join(temp, 'mountains.svg'));
  await fs.writeFile(fixture, '# 图片缩放测试\n\n![山间留白](mountains.svg)\n\n## 第二章\n\n文字缩放与图片宽度独立保存。\n\n```md\n![山间留白](mountains.svg)\n```\n\n![山间留白](mountains.svg)\n');
  let app;
  try {
    const env = { ...process.env, MOYE_TEST_PROFILE: path.join(temp, 'profile') }; delete env.ELECTRON_RUN_AS_NODE;
    app = await electron.launch({ executablePath: require('electron'), args: [root, fixture], env, timeout: 60000 });
    const page = await app.firstWindow();
    page.setDefaultTimeout(15000);
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.waitForFunction(() => document.querySelector('#preview img')?.naturalWidth === 1200);
    assert.equal(await page.locator('#fileName').textContent(), '测试文档.md');
    await page.locator('[data-zoom="preview:1"]').click();
    assert.equal(await page.locator('#previewZoom').textContent(), '110%');
    assert.equal(await page.locator('#editorZoom').textContent(), '100%');
    await page.locator('#previewZoom').click();
    await page.locator('#preview img').first().click();
    await page.locator('#imageWidth').fill('320'); await page.locator('#imageWidth').press('Enter');
    await page.waitForFunction(() => document.querySelector('#preview img')?.getAttribute('width') === '320');
    const resized = await page.locator('#editor').inputValue();
    assert.ok(resized.includes('<img src="mountains.svg" alt="山间留白" width="320">'));
    assert.ok(resized.includes('```md\n![山间留白](mountains.svg)\n```'));
    await page.locator('#saveBtn').click();
    await page.waitForFunction(() => document.querySelector('#saveState').textContent === '已保存');
    assert.ok((await fs.readFile(fixture, 'utf8')).includes('width="320"'));
    await page.locator('#preview img').first().click();
    const handle = await page.locator('.resize-handle').first().boundingBox();
    await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2); await page.mouse.down(); await page.mouse.move(handle.x + handle.width / 2 + 60, handle.y + handle.height / 2 + 30); await page.mouse.up();
    await page.waitForFunction(() => document.querySelector('#preview img')?.getAttribute('width') === '380');
    await page.locator('#saveBtn').click();
    const relocated = path.join(temp, '另存目录', '新文档.md'); await fs.mkdir(path.dirname(relocated));
    await app.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, relocated);
    await page.locator('#saveAsBtn').click();
    await page.waitForFunction(() => document.querySelector('#fileName').textContent === '新文档.md');
    assert.ok((await fs.readFile(relocated, 'utf8')).includes('../mountains.svg'));
    await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, fixture);
    await page.locator('#openBtn').click();
    await page.waitForFunction(() => document.querySelector('#fileName').textContent === '测试文档.md' && document.querySelector('#preview img')?.getAttribute('width') === '380');
    await page.locator('#preview img').first().dblclick();
    assert.equal(await page.locator('#lightbox').evaluate(e => e.open), true);
    await page.locator('#viewerPlus').click();
    assert.notEqual(await page.locator('#viewerPercent').textContent(), '100%');
    await page.locator('#viewerOriginal').click(); assert.equal(await page.locator('#viewerPercent').textContent(), '100%');
    const stage = await page.locator('#imageStage').boundingBox();
    await page.mouse.move(stage.x + 100, stage.y + 100); await page.mouse.down(); await page.mouse.move(stage.x + 170, stage.y + 140); await page.mouse.up();
    assert.ok((await page.locator('#largeImage').getAttribute('style')).includes('translate'));
    await page.keyboard.press('Escape');
    await app.evaluate(({ dialog }, imagePath) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [imagePath] }); }, image);
    await page.locator('#editor').focus(); await page.locator('#editor').press('Control+End');
    await page.locator('#imageBtn').click();
    await page.waitForFunction(() => document.querySelector('#editor').value.includes('测试文档.assets/'));
    assert.equal((await fs.readdir(path.join(temp, '测试文档.assets'))).length, 1);
    await page.locator('#editor').focus(); await page.keyboard.press('Control+z');
    assert.ok(!(await page.locator('#editor').inputValue()).includes('测试文档.assets/'));
    await page.keyboard.press('Control+y');
    assert.ok((await page.locator('#editor').inputValue()).includes('测试文档.assets/'));
    const malicious = '\n<script>window.PWNED=true</script><img src="x" onerror="window.PWNED=true"><iframe src="https://example.com"></iframe>';
    await page.locator('#editor').fill((await page.locator('#editor').inputValue()) + malicious);
    await page.waitForTimeout(350);
    assert.equal(await page.evaluate(() => window.PWNED), undefined);
    assert.equal(await page.locator('#preview script,#preview iframe,#preview [onerror]').count(), 0);
    await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 2 }); });
    const before = await page.locator('#editor').inputValue(); await page.locator('#newBtn').click();
    await page.waitForTimeout(100); assert.equal(await page.locator('#editor').inputValue(), before);
    await page.locator('#editor').fill('# 外部修改检查');
    await fs.writeFile(fixture, '# 外部版本');
    await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 0 }); });
    await page.locator('#saveBtn').click(); await page.waitForTimeout(150);
    assert.equal(await fs.readFile(fixture, 'utf8'), '# 外部版本');
    await app.evaluate(({ dialog }, sample) => { dialog.showMessageBox = async () => ({ response: 1 }); dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [sample] }); }, path.join(root, '示例文档.md'));
    await page.locator('#openBtn').click();
    await page.waitForFunction(() => document.querySelector('#fileName').textContent === '示例文档.md' && document.querySelector('#preview img')?.naturalWidth > 0);
    await fs.mkdir(path.join(root, 'test-results'), { recursive: true });
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].showInactive());
    await page.screenshot({ path: path.join(root, 'test-results', 'editor.png'), timeout: 15000 });
    await page.locator('#preview img').first().dblclick();
    await page.screenshot({ path: path.join(root, 'test-results', 'image-viewer.png'), timeout: 15000 });
    assert.deepEqual(errors, []);
    console.log('PASS: open, independent zoom, precise image resize, save, viewer zoom/pan, image import, undo/redo, sanitization, unsaved cancel, external conflict, screenshots');
  } finally { if (app) { await app.evaluate(({ app }) => { setTimeout(() => app.exit(0), 50); }).catch(() => {}); await app.close().catch(() => {}); } await fs.rm(temp, { recursive: true, force: true, maxRetries: 5, retryDelay: 250 }); }
})().catch(error => { console.error(error); process.exitCode = 1; });
