const {_electron:electron}=require('playwright'),fs=require('fs/promises'),path=require('path'),os=require('os'),assert=require('assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),temp=await fs.mkdtemp(path.join(os.tmpdir(),'moye-recovery-'));let app,page;const packaged=process.argv.includes('--packaged');
async function launch(){const env={...process.env,MOYE_TEST_PROFILE:temp};delete env.ELECTRON_RUN_AS_NODE;app=await electron.launch({executablePath:packaged?path.join(root,require('../package.json').build.directories.output,'win-unpacked/成简.exe'):require('electron'),args:packaged?[]:[root],env});page=await app.firstWindow();page.setDefaultTimeout(12000);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive());await page.waitForSelector('.tiptap');}
async function stop(){if(app){await app.evaluate(({app})=>setTimeout(()=>app.exit(0),30));await app.close().catch(()=>{});app=null;}}
try{await launch();await page.locator('#fileMenuBtn').click(); await page.locator('#newBtn').click();await page.waitForFunction(()=>document.querySelector('.tiptap').textContent==='');await page.locator('.tiptap').click();await page.keyboard.insertText('恢复测试');
await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},path.join(root,'assets/mountains.svg'));await page.locator('#imageBtn').click();await page.waitForFunction(()=>document.querySelector('.tiptap .rich-image img')?.naturalWidth===1200);await page.waitForFunction(()=>document.querySelector('#saveState').textContent==='草稿已保存');
await stop();await launch();assert.match(await page.locator('.tiptap').innerText(),/恢复测试/);await page.waitForFunction(()=>document.querySelector('.tiptap .rich-image img')?.naturalWidth===1200);
const file=path.join(temp,'恢复.md');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},file);await page.locator('#fileMenuBtn').click(); await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.querySelector('#saveState').textContent==='已保存');assert.match(await fs.readFile(file,'utf8'),/恢复\.assets/);assert.ok((await fs.readdir(path.join(temp,'恢复.assets'))).length);
await fs.writeFile(file,'外部版本');await page.locator('.tiptap').click();await page.keyboard.press('Control+Home');await page.keyboard.insertText('修改');await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('自动保存已暂停'));assert.equal(await fs.readFile(file,'utf8'),'外部版本');
await page.locator('#colorsBtn').click();await page.locator('#newScheme').click();await page.locator('#backgroundType').selectOption('image');await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},path.join(root,'assets/app-icon.png'));await page.locator('#uploadThemeImage').click();await page.waitForFunction(()=>document.querySelector('#themeThumbnail').naturalWidth>0);await page.locator('#themeScale').fill('150');await page.locator('#themeBlur').fill('5');await page.locator('#themeOpacity').fill('65');assert.match(await page.locator('#themeBackdrop').evaluate(e=>e.style.backgroundImage),/file:/);await page.locator('#applyColors').click();await page.locator('#schemesDialog button.primary').click();
await page.reload();await page.waitForSelector('.tiptap');assert.equal(await page.locator('#themeBackdrop').evaluate(e=>e.style.opacity),'0.65');assert.equal(await page.locator('#themeBackdrop').evaluate(e=>e.style.transform),'scale(1.5)');
await page.locator('#fileMenuBtn').click(); await page.locator('#newBtn').click();await page.waitForFunction(()=>document.querySelector('.tiptap').textContent==='');await page.locator('.tiptap').click();await page.keyboard.insertText('源格式');await page.keyboard.press('Enter');await page.keyboard.insertText('目标文字');await page.locator('.tiptap p').filter({hasText:'源格式'}).click({position:{x:8,y:10}});await page.keyboard.press('Home');await page.keyboard.press('Shift+End');await page.locator('[data-command=bold]').click();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await page.locator('.tiptap p').first().locator('strong').count(),1);await page.locator('#brushBtn').click();await page.locator('.tiptap p').nth(1).click({clickCount:3});await page.waitForFunction(()=>document.querySelectorAll('.tiptap strong').length===2);
await app.evaluate(async({BrowserWindow})=>{const data=await BrowserWindow.getAllWindows()[0].webContents.printToPDF({printBackground:true});if(data.length<1000)throw new Error('empty PDF');});
console.log('PASS: restart recovery with images, portable assets after save, external conflict protection, theme image upload/persistence, format painter and PDF rendering.');
}finally{await stop().catch(()=>{});await fs.rm(temp,{recursive:true,force:true,maxRetries:5,retryDelay:250});}})().catch(e=>{console.error(e);process.exitCode=1;});


