const {_electron:electron}=require('playwright');const fs=require('fs/promises'),os=require('os'),path=require('path'),assert=require('assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),profile=await fs.mkdtemp(path.join(os.tmpdir(),'chengjian-theme-menu-'));let app;try{const env={...process.env,MOYE_TEST_PROFILE:profile};delete env.ELECTRON_RUN_AS_NODE;app=await electron.launch({executablePath:require('electron'),args:[root],env});const page=await app.firstWindow();await page.waitForSelector('.tiptap');await page.locator('#colorsBtn').click();await page.locator('#newScheme').click();const button=page.locator('#backgroundType + .glass-select-button');
for(const label of ['纯色','渐变色','上传图片']){
 await button.scrollIntoViewIfNeeded();const before=await page.locator('#colorsDialog').evaluate(e=>({left:e.scrollLeft,width:e.clientWidth}));await button.click();const box=await button.boundingBox(),menu=await page.locator('.glass-select-menu').boundingBox();const state=await page.locator('#colorsDialog').evaluate(e=>({left:e.scrollLeft,width:e.clientWidth,content:e.scrollWidth}));
 assert.equal(state.left,before.left,'Opening menu must not scroll dialog horizontally');assert.ok(state.content<=state.width+1,'No horizontal overflow');assert.ok(Math.abs(menu.x-box.x)<2,'Menu aligns with its button');assert.ok(Math.abs(menu.y-(box.y+box.height+5))<2 || Math.abs(menu.y+menu.height+5-box.y)<2,'Menu sits immediately above or below the button');
 await page.getByRole('option',{name:label,exact:true}).click();assert.equal(await button.textContent(),label+' ▾');assert.equal(await page.locator('.glass-select-menu').count(),0);assert.equal(await page.locator('#gradientControls').evaluate(e=>e.hidden),label!=='渐变色');assert.equal(await page.locator('#imageControls').evaluate(e=>e.hidden),label!=='上传图片');const type=await page.evaluate(()=>{const data=JSON.parse(localStorage.getItem('moye.color.schemes'));return data.schemes.find(s=>s.id===data.selected).effects.type;});assert.equal(type,({'纯色':'solid','渐变色':'gradient','上传图片':'image'})[label]);
}
await button.click();await page.keyboard.press('Escape');assert.equal(await page.locator('.glass-select-menu').count(),0);assert.equal(await page.locator('#colorsDialog').evaluate(e=>e.open),true);
await fs.mkdir(path.join(root,'test-results'),{recursive:true});await page.screenshot({path:path.join(root,'test-results/theme-menu-fixed.png')});console.log('PASS: theme choices remain anchored, no dialog overflow, all three modes switch, Escape closes only menu');
}finally{if(app){await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{});}await fs.rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:200});}})().catch(e=>{console.error(e);process.exitCode=1;});
