const {_electron:electron}=require('playwright'),fs=require('fs/promises'),path=require('path'),os=require('os'),assert=require('assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),temp=await fs.mkdtemp(path.join(os.tmpdir(),'moye-v4-'));let app;
try{const env={...process.env,MOYE_TEST_PROFILE:temp};delete env.ELECTRON_RUN_AS_NODE;const packaged=process.argv.includes('--packaged');app=await electron.launch({executablePath:packaged?path.join(root,require('../package.json').build.directories.output,'win-unpacked/成简.exe'):require('electron'),args:packaged?[]:[root],env});const page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>console.error('PAGE ERROR',e));await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].showInactive();});await page.waitForSelector('.tiptap');await page.locator('#fileMenuBtn').click(); await page.locator('#autoSave').uncheck(); await page.locator('#fileMenuBtn').click();
assert.equal(await page.locator('#colorsBtn').textContent(),'主题');
await page.locator('#fileMenuBtn').click(); await page.locator('#newBtn').click();await page.waitForFunction(()=>document.querySelector('.tiptap').textContent==='');const doc=page.locator('.tiptap');await doc.click();await page.keyboard.insertText('项目概况');await page.keyboard.press('Control+a');await page.locator('#highlightBtn').click();assert.equal(await doc.locator('mark').count(),1);await page.locator('#highlightMenuBtn').click();assert.equal(await page.locator('#highlightPalette').innerText(),'');await page.locator('[data-color="#90caf9"]').click();
await page.locator('[data-command=ordered]').click();await page.locator('#blockType').selectOption('1',{force:true});assert.equal(await doc.locator('ol h1').filter({hasText:'项目概况'}).count(),1,await doc.innerHTML());
await page.locator('#numberMenuBtn').click();await page.locator('[data-numbering="chinese-paren"]').last().click();assert.equal(await doc.locator('ol h1').filter({hasText:'项目概况'}).count(),1,await doc.innerHTML());await page.locator('[data-command=ordered]').click();assert.equal(await doc.locator('ol').count(),0);assert.equal(await doc.locator('h1').count(),1);await page.locator('[data-command=ordered]').click();assert.equal(await doc.locator('ol').getAttribute('data-numbering'),'decimal');
await page.locator('#fileName').dblclick();await page.locator('#inlineFileName').fill('原位改名');await page.locator('#inlineFileName').press('Enter');await page.waitForFunction(()=>document.querySelector('#fileName').textContent==='原位改名.md');assert.equal(await page.locator('#renameDialog').count(),0);
await page.locator('#floatBtn').click();assert.equal(await page.locator('.topbar').isVisible(),false);assert.equal(await page.locator('#imageBtn').isVisible(),false);await page.locator('#restoreWindowBtn').click();
await page.locator('#colorsBtn').click();await page.locator('#newScheme').click();await page.locator('#schemeName').fill('可删除主题');await page.locator('#applyColors').click();await page.getByRole('button',{name:'删除 可删除主题',exact:true}).click();assert.equal(await page.getByRole('button',{name:'可删除主题',exact:true}).count(),0);await page.locator('#schemesDialog button.primary').click();

assert.equal(await page.locator('#importWordBtn,#formulaBtn').count(),0);
await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:1});});
await page.locator('#fileMenuBtn').click(); await page.locator('#newBtn').click();await page.waitForFunction(()=>document.querySelector('.tiptap').textContent==='');

await doc.click();await page.keyboard.insertText('源标题');await page.keyboard.press('Enter');await page.keyboard.insertText('目标段落');await doc.locator('p').filter({hasText:'源标题'}).click({position:{x:8,y:10}});await page.keyboard.press('Home');await page.keyboard.press('Shift+End');await page.locator('#blockType').selectOption('2',{force:true});await page.locator('#numberMenuBtn').click();await page.locator('#numberMenu [data-numbering="chinese"]').click();await page.locator('#brushBtn').click();await doc.locator('p').filter({hasText:'目标段落'}).click({clickCount:3});await page.waitForFunction(()=>document.querySelectorAll('.tiptap ol[data-numbering="chinese"] h2').length===2);
await page.locator('#fileMenuBtn').click(); await page.locator('#newBtn').click();await page.waitForFunction(()=>document.querySelector('.tiptap').textContent==='');
const image=path.join(root,'test-results/native-word.files/image001.png');
const html='<p style="mso-margin-top-alt:auto">公式前 <img width="7" height="42" src="'+require('url').pathToFileURL(image).href+'"> 公式后</p>';
await doc.click();await doc.evaluate((el,html)=>{const data=new DataTransfer();data.setData('text/html',html);el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},html);
await page.waitForFunction(()=>document.querySelector('.tiptap .rich-image img')?.naturalWidth>0);
const equationP=doc.locator('p').filter({hasText:'公式前'});assert.equal(await equationP.locator('img').count(),1);
const paragraph=await equationP.innerHTML();assert.ok(paragraph.indexOf('公式前')<paragraph.indexOf('<img'));assert.ok(paragraph.indexOf('公式后')>paragraph.indexOf('<img'));
const src=await equationP.locator('img').getAttribute('src');assert.deepEqual(await fs.readFile(require('url').fileURLToPath(src)),await fs.readFile(image));
const save=path.join(temp,'公式图片.md');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},save);await page.locator('#fileMenuBtn').click(); await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.querySelector('#saveState').textContent==='已保存');await page.locator('#fileMenuBtn').click(); await page.locator('#openBtn').click();await page.waitForFunction(()=>document.querySelector('.tiptap .rich-image img')?.naturalWidth>0);assert.equal(await doc.locator('p').filter({hasText:'公式前'}).locator('img').count(),1);
await page.screenshot({path:path.join(root,'test-results/v4-workbench.png')});console.log('PASS: split menus, numbered headings, inline rename, compact float, theme deletion, Word file import absent, native equation image clipboard and roundtrip.');
}finally{if(app){await app.evaluate(({app})=>setTimeout(()=>app.exit(0),50)).catch(()=>{});await app.close().catch(()=>{});}await fs.rm(temp,{recursive:true,force:true,maxRetries:5,retryDelay:250});}})().catch(e=>{console.error(e);process.exitCode=1;});
